export const CHANGE_PLAYING_SONG = "player/CHANGE_PLAYING_SONG";
export const CHANGE_PLAYING_SONG_IDX = "player/CHANGE_PLAYING_SONG_IDX";
export const CHANGE_PLAY_LIST = "player/CHANGE_PLAY_LIST";
export const CHANGE_PLAY_WAY = "player/CHANGE_PLAY_WAY"
